import { randomUUID } from "node:crypto";
import { NextResponse } from "next/server";
import { z } from "zod";
import { createManagedTemplateVersion, listManagedTemplates, listManagedTemplateVersions } from "@cardelume/db";
import { portfolioV2AllTemplates } from "@cardelume/templates";
const allowed=new Map(portfolioV2AllTemplates.map(t=>[t.rendererTemplateKey,t]));
const Id=z.string().uuid();
const Input=z.object({rendererTemplateKey:z.string().min(2).max(80),supportedFormats:z.array(z.string().min(2).max(40)).min(1).max(8).default(["portrait-5x7"]),scriptSupport:z.array(z.enum(["latin","cjk","hangul"])).min(1).max(3).default(["latin","cjk","hangul"]),headlineCapacity:z.enum(["short","medium","long"]).default("medium"),bodyCapacity:z.enum(["short","medium","long"]).default("medium"),activate:z.boolean().default(false)});
export async function GET(_:Request,{params}:{params:Promise<{templateId:string}>}){const {templateId}=await params;const id=Id.safeParse(templateId);if(!id.success)return NextResponse.json({error:"template_id_invalid"},{status:400});try{return NextResponse.json({versions:await listManagedTemplateVersions({templateId:id.data})},{headers:{"cache-control":"no-store"}});}catch{return NextResponse.json({error:"template_versions_unavailable"},{status:503});}}
export async function POST(req:Request,{params}:{params:Promise<{templateId:string}>}){const {templateId}=await params;const id=Id.safeParse(templateId),body=Input.safeParse(await req.json().catch(()=>null));if(!id.success||!body.success)return NextResponse.json({error:"template_version_invalid"},{status:400});const approvedRenderer=allowed.get(body.data.rendererTemplateKey);if(!approvedRenderer)return NextResponse.json({error:"renderer_template_key_not_approved"},{status:409});const visualDirection=approvedRenderer.visualDirection;
const unsupportedFormat=body.data.supportedFormats.some(x=>!approvedRenderer.supportedFormats.includes(x));const unsupportedScript=body.data.scriptSupport.some(x=>!approvedRenderer.scriptSupport.includes(x));if(unsupportedFormat||unsupportedScript)return NextResponse.json({error:"renderer_capability_expansion_not_approved"},{status:409});try{const template=(await listManagedTemplates({includeInactive:true})).find(t=>t.id===id.data);if(!template)return NextResponse.json({error:"template_not_found"},{status:404});if(approvedRenderer.photoMode!==template.photoMode)return NextResponse.json({error:"photo_mode_renderer_mismatch"},{status:409});return NextResponse.json(await createManagedTemplateVersion({templateId:id.data,versionId:randomUUID(),...body.data,visualDirection,validationStatus:"passed",validationNotes:"Created from a repo-registered CardeLume renderer key; launch approval remains separate and version activation invalidates prior launch approval."}),{status:201});}catch(error){return NextResponse.json({error:error instanceof Error?error.message:"template_version_create_failed"},{status:409});}}
