import type { LocaleCode } from "./messages";

export type LegalSection={title:string;body:string};
export type LegalCopy={
  privacyTitle:string;privacyIntro:string;privacySections:LegalSection[];
  termsTitle:string;termsIntro:string;termsSections:LegalSection[];
  refundTitle:string;refundIntro:string;refundSections:LegalSection[];
  contactTitle:string;effectiveLabel:string;
};

const en:LegalCopy={
  privacyTitle:"Privacy Policy",privacyIntro:"CardeLume is an early public beta for creating and downloading digital greeting-card files. Payment and checkout are currently unavailable; beta JPG and print-ready PDF downloads are provided at no charge. CardeLume is designed to use the minimum personal data reasonably needed for that service.",effectiveLabel:"Effective date",contactTitle:"Support, privacy and legal contact",
  privacySections:[
    {title:"What we process",body:"We may process an anonymous session identifier, your card brief and message, locale and market, an optional uploaded photo, card and download identifiers, and privacy-minimized product telemetry. We process this data to create, render, deliver and support requested CardeLume outputs, protect the service, measure its use and meet applicable legal or accounting needs. We do not need an account for the beta create → download flow. CardeLume does not collect payment-card details or create a paid order through the beta download flow."},
    {title:"AI and card creation",body:"Card brief text may be sent to the configured AI provider to create copy and creative directions. The original uploaded photo bytes are not sent to the creative AI in the current design; derived photo characteristics may be used for art direction. AI-assisted wording and directions can be inaccurate or non-unique, so review the result before downloading or sharing."},
    {title:"Uploaded photos",body:"If you upload a photo, it is accepted only in supported image formats, processed in private quarantine storage, checked and sanitized for rendering, and converted to a clean JPEG. It is not made public or sent to the creative AI as original bytes. Temporary upload objects are eligible for cleanup under the service's configured retention process; upload only material you have permission to use."},
    {title:"Payment status and service providers",body:"Payment and checkout are currently disabled during the public beta. No charge, paid order, paid entitlement, or payment-card data is created or collected through the beta download flow. If a paid service is introduced later, the relevant payment-provider terms and updated legal copy will be published before activation. The configured AI provider may process card brief text only to provide AI-assisted CardeLume creation; other infrastructure providers may process data only to provide CardeLume storage, rendering, delivery, security or support functions under their applicable terms."},
    {title:"Analytics and logs",body:"Funnel analytics use a pseudonymous hash rather than the raw anonymous session identifier and are designed not to contain greeting copy, recipient names, uploaded photo contents or payment credentials. Security logs are likewise intended to avoid secrets and customer content."},
    {title:"Retention",body:"Temporary photo uploads are eligible for cleanup after the configured quarantine period, currently 120 minutes by default. Completed generation results are retained for a bounded period, currently 7 days by default; analytics and AI-usage records use configured bounded periods. These defaults may change as the service is operated, and legal, security or accounting records may need to be retained longer."},
    {title:"Your choices",body:"You may choose not to upload a photo. You may use the email shown below to contact CardeLume for beta-download support or to request access, correction or deletion where applicable; legal, fraud-prevention, security or accounting records may need to be retained."},
    {title:"International processing and security",body:"CardeLume is an international digital service, so service providers may process data outside Vietnam or your country when needed to provide CardeLume, subject to applicable safeguards and law. We use access controls, private object storage, short-lived signed downloads, rate limits and other safeguards, but no online service can promise absolute security."}
  ],
  termsTitle:"Terms of Use",termsIntro:"These terms apply to CardeLume's public beta digital greeting-card creation and download service. Payment and checkout are currently unavailable; no purchase is made through the beta.",
  termsSections:[
    {title:"Digital product",body:"CardeLume provides digital files: a JPG and a print-ready PDF. No physical card is shipped. During the public beta, these files are provided at no charge. If a paid offering is introduced later, its payment and delivery terms will be published before activation."},
    {title:"Your content and rights",body:"You retain the rights in the photos, names, text and other content you provide. You grant CardeLume a limited, non-exclusive license solely to process that content and generate, render, store, deliver and support the outputs you request. You represent that you have the rights or permission needed to upload and use the content, and remain responsible for what you submit."},
    {title:"Prohibited use",body:"Do not upload clearly unlawful or infringing material, violate third-party rights, impersonate others deceptively, distribute malware, exploit children, or create content that the service is not permitted to process. CardeLume may refuse or remove content when necessary for safety, security, law or rights protection."},
    {title:"AI and originality",body:"CardeLume may use AI to assist with wording and creative directions. AI-generated or AI-assisted output is not guaranteed to be unique, exclusive, accurate, or free of similarity to third-party material; you are responsible for reviewing it before use or sharing. CardeLume controls its production template library and provenance process, but does not promise exclusive rights in generic phrases, ideas, styles, typefaces or other elements that law may not protect."},
    {title:"Beta downloads and future payment",body:"The public beta provides selected JPG and print-ready PDF downloads at no charge. Payment, checkout, paid orders and paid entitlements are unavailable in this beta. CardeLume does not promise that a future paid service will be available or that beta files will receive any paid-service rights."},
    {title:"Availability and changes",body:"CardeLume may improve models, templates, infrastructure and features over time. Temporary outages, provider failures or maintenance may delay or prevent creation and download. CardeLume may change or end the public beta with reasonable notice where practicable."},
    {title:"Intellectual-property reports",body:"If you believe material available through CardeLume infringes your rights, contact the legal address shown below with enough detail to identify the work, the material at issue, your authority and a reliable way to reach you. CardeLume will review good-faith reports and preserve appropriate evidence."}
  ],
  refundTitle:"Payment Status & Refunds",refundIntro:"Payment and checkout are currently unavailable during the public beta. No payments are accepted during the CardeLume public beta. Therefore no payment refund transaction applies during this phase. Beta JPG and PDF downloads are provided at no charge. If paid checkout is activated later, applicable payment and refund terms will be updated before activation; mandatory consumer rights always prevail.",
  refundSections:[
    {title:"Beta download support",body:"Contact support if a beta download is missing, corrupted, or materially different from the selected result because of a CardeLume error. We may re-render, correct or otherwise provide the affected beta file where reasonably possible."},
    {title:"Before payment activation",body:"CardeLume does not accept payment, create paid orders, or issue paid entitlements during this beta. There is therefore no paid transaction to refund through the beta download flow."},
    {title:"Future paid service",body:"Any future paid quality guarantee, refund process, delivery promise or Merchant of Record terms will be published before payment is enabled. Those terms will not be inferred from this no-charge beta."},
    {title:"Abuse and exclusions",body:"Support may be limited where a request involves fraud, repeated abuse, unlawful material, or content the customer was not authorized to submit. Mandatory legal rights remain unaffected."}
  ]
};

function localized(base:LegalCopy,overrides:Partial<LegalCopy>):LegalCopy{return{...base,...overrides};}

export const legalCopy:Record<LocaleCode,LegalCopy>={
  en,
  vi:localized(en,{privacyTitle:"Chính sách quyền riêng tư",privacyIntro:"CardeLume được thiết kế để tạo và giao thiệp kỹ thuật số với lượng dữ liệu cá nhân tối thiểu cần thiết cho dịch vụ.",termsTitle:"Điều khoản sử dụng",termsIntro:"Các điều khoản này áp dụng cho việc tạo, xem trước, mua và tải thiệp kỹ thuật số trên CardeLume.",refundTitle:"Hoàn tiền & Đảm bảo chất lượng lần mua đầu",refundIntro:"Quyền lợi bắt buộc của người tiêu dùng và quy định của Merchant of Record/nhà cung cấp thanh toán luôn được ưu tiên. CardeLume cũng hướng đến cách xử lý thực tế cho lỗi giao hàng hoặc chất lượng thật sự.",contactTitle:"Liên hệ về quyền riêng tư và pháp lý",effectiveLabel:"Ngày hiệu lực"}),
  ja:localized(en,{privacyTitle:"プライバシーポリシー",privacyIntro:"CardeLume は、デジタルグリーティングカードの作成と提供に合理的に必要な最小限の個人データで動作するよう設計されています。",termsTitle:"利用規約",termsIntro:"本規約は CardeLume のカード作成、プレビュー、購入、ダウンロードサービスに適用されます。",refundTitle:"返金・初回購入品質保証",refundIntro:"法令上の消費者権利および Merchant of Record／決済事業者の必須ルールが常に優先されます。",contactTitle:"プライバシー・法務窓口",effectiveLabel:"発効日"}),
  ko:localized(en,{privacyTitle:"개인정보 처리방침",privacyIntro:"CardeLume는 디지털 카드 제작과 전달에 합리적으로 필요한 최소한의 개인정보만 처리하도록 설계되었습니다.",termsTitle:"이용약관",termsIntro:"본 약관은 CardeLume의 카드 제작, 미리보기, 구매 및 다운로드 서비스에 적용됩니다.",refundTitle:"환불 및 첫 구매 품질 보장",refundIntro:"법정 소비자 권리와 Merchant of Record/결제 제공자의 의무 규정이 항상 우선합니다.",contactTitle:"개인정보·법률 문의",effectiveLabel:"시행일"}),
  es:localized(en,{privacyTitle:"Política de privacidad",privacyIntro:"CardeLume está diseñado para crear y entregar tarjetas digitales utilizando únicamente los datos personales razonablemente necesarios para prestar el servicio.",termsTitle:"Términos de uso",termsIntro:"Estos términos se aplican a la creación, vista previa, compra y descarga de tarjetas digitales de CardeLume.",refundTitle:"Reembolsos y garantía de calidad de la primera compra",refundIntro:"Los derechos legales del consumidor y las reglas obligatorias del Merchant of Record/proveedor de pagos prevalecen siempre.",contactTitle:"Contacto de privacidad y legal",effectiveLabel:"Fecha de vigencia"}),
  fr:localized(en,{privacyTitle:"Politique de confidentialité",privacyIntro:"CardeLume est conçu pour créer et livrer des cartes numériques avec le minimum de données personnelles raisonnablement nécessaire au service.",termsTitle:"Conditions d’utilisation",termsIntro:"Ces conditions s’appliquent à la création, l’aperçu, l’achat et au téléchargement de cartes numériques CardeLume.",refundTitle:"Remboursements et garantie qualité du premier achat",refundIntro:"Les droits légaux des consommateurs et les règles obligatoires du Merchant of Record/prestataire de paiement prévalent toujours.",contactTitle:"Contact confidentialité et juridique",effectiveLabel:"Date d’entrée en vigueur"}),
  de:localized(en,{privacyTitle:"Datenschutzerklärung",privacyIntro:"CardeLume ist darauf ausgelegt, digitale Grußkarten mit möglichst wenigen, für den Dienst erforderlichen personenbezogenen Daten zu erstellen und bereitzustellen.",termsTitle:"Nutzungsbedingungen",termsIntro:"Diese Bedingungen gelten für Erstellung, Vorschau, Kauf und Download digitaler CardeLume-Karten.",refundTitle:"Rückerstattung & Qualitätsgarantie beim ersten Kauf",refundIntro:"Gesetzliche Verbraucherrechte und zwingende Regeln des Merchant of Record/Zahlungsanbieters haben stets Vorrang.",contactTitle:"Datenschutz- und Rechtskontakt",effectiveLabel:"Gültig ab"}),
  pt:localized(en,{privacyTitle:"Política de privacidade",privacyIntro:"O CardeLume foi projetado para criar e entregar cartões digitais usando apenas os dados pessoais razoavelmente necessários para o serviço.",termsTitle:"Termos de uso",termsIntro:"Estes termos se aplicam à criação, prévia, compra e download de cartões digitais no CardeLume.",refundTitle:"Reembolso e garantia de qualidade da primeira compra",refundIntro:"Direitos legais do consumidor e regras obrigatórias do Merchant of Record/provedor de pagamentos sempre prevalecem.",contactTitle:"Contato de privacidade e jurídico",effectiveLabel:"Data de vigência"}),
  it:localized(en,{privacyTitle:"Informativa sulla privacy",privacyIntro:"CardeLume è progettato per creare e consegnare biglietti digitali usando solo i dati personali ragionevolmente necessari al servizio.",termsTitle:"Termini di utilizzo",termsIntro:"Questi termini si applicano alla creazione, anteprima, acquisto e download dei biglietti digitali CardeLume.",refundTitle:"Rimborsi e garanzia qualità sul primo acquisto",refundIntro:"I diritti inderogabili dei consumatori e le regole obbligatorie del Merchant of Record/fornitore di pagamento prevalgono sempre.",contactTitle:"Contatto privacy e legale",effectiveLabel:"Data di efficacia"}),
  zh:localized(en,{privacyTitle:"隐私政策",privacyIntro:"CardeLume 的设计目标是在创建和交付数字贺卡时，只处理提供服务所合理需要的最少个人数据。",termsTitle:"使用条款",termsIntro:"本条款适用于 CardeLume 的数字贺卡创建、预览、购买和下载服务。",refundTitle:"退款与首次购买质量保障",refundIntro:"法定消费者权利以及 Merchant of Record/支付服务商的强制规则始终优先适用。",contactTitle:"隐私与法律联系",effectiveLabel:"生效日期"})
};
