import type { LocaleCode } from "./messages";

export type LegalSection={title:string;body:string};
export type LegalCopy={
  privacyTitle:string;privacyIntro:string;privacySections:LegalSection[];
  termsTitle:string;termsIntro:string;termsSections:LegalSection[];
  refundTitle:string;refundIntro:string;refundSections:LegalSection[];
  contactTitle:string;effectiveLabel:string;
};

const en:LegalCopy={
  privacyTitle:"Privacy Policy",privacyIntro:"CardeLume is designed to create and deliver digital greeting cards with the minimum personal data reasonably needed for that service.",effectiveLabel:"Effective date",contactTitle:"Privacy and legal contact",
  privacySections:[
    {title:"What we process",body:"We may process an anonymous session identifier, your card brief and message, locale and market, optional uploaded photo, card and order identifiers, payment status, download/recovery records, and privacy-minimized product telemetry. We do not need an account for the core create → pay → download flow."},
    {title:"AI and card creation",body:"Card brief text may be sent to the configured AI provider to create copy and creative directions. CardeLume does not send the original uploaded photo bytes to the creative AI in the current production design; derived photo characteristics may be used for art direction. Uploaded photos are processed for card rendering and kept in private storage."},
    {title:"Payments and service providers",body:"Checkout is handled by the configured Merchant of Record/payment provider. CardeLume stores order and payment-status metadata needed to deliver the purchase, but does not intentionally store full payment-card credentials. Infrastructure providers may process data for database, object storage, AI, error monitoring and delivery functions under their applicable terms."},
    {title:"Analytics and logs",body:"Funnel analytics use a pseudonymous hash rather than the raw anonymous session identifier and are designed not to contain greeting copy, recipient names, uploaded photo contents or payment credentials. Security logs are likewise intended to avoid secrets and customer content."},
    {title:"Retention",body:"Operational records are kept only for configured service, security, recovery and accounting periods. Current defaults include short-lived generation results, limited AI-usage telemetry, and bounded analytics/style-history retention. Purchase/recovery data and paid files may be kept longer to provide secure re-downloads and meet legal or accounting duties."},
    {title:"Your choices",body:"You may choose not to upload a photo. Where optional style memory or an account is introduced, it must remain opt-in and resettable. You may contact CardeLume to request access, correction or deletion where applicable; legal, fraud-prevention, accounting or completed-transaction records may need to be retained."},
    {title:"International processing and security",body:"CardeLume is an international digital service, so service providers may process data in more than one country. We use access controls, private object storage, short-lived signed downloads, verified payment webhooks, rate limits and other safeguards, but no online service can promise absolute security."}
  ],
  termsTitle:"Terms of Use",termsIntro:"These terms apply to CardeLume’s digital greeting-card creation, preview, purchase and download service.",
  termsSections:[
    {title:"Digital product",body:"CardeLume provides digital files. No physical card is shipped. A purchase unlocks the selected card’s clean high-resolution JPG and print-ready PDF, subject to successful payment and rendering."},
    {title:"Your content and rights",body:"You must have the rights or permission needed to upload photos, names, text and other material you provide. You grant CardeLume only the limited permission needed to process that material to create, render, store, deliver and support your requested card. You remain responsible for the material you submit."},
    {title:"Prohibited use",body:"Do not use CardeLume to violate law or third-party rights, impersonate others deceptively, distribute malware, exploit children, or create content that the service is not permitted to process. CardeLume may refuse or remove content when necessary for safety, security, law or rights protection."},
    {title:"AI and originality",body:"AI-assisted copy and art direction can vary and may not be unique to one customer. CardeLume controls its production template library and provenance process, but does not promise exclusive rights in generic phrases, ideas, styles, typefaces or other elements that law may not protect."},
    {title:"Preview, payment and delivery",body:"Unpaid previews may include a watermark and reduced-resolution rendering. Clean final files are released only after server-side payment verification. Prices and currency are shown before checkout; the payment provider’s checkout terms also apply."},
    {title:"Availability and changes",body:"CardeLume may improve models, templates, pricing, infrastructure and features over time. Existing paid entitlements remain tied to the purchased card/version as described by the service. Temporary outages, provider failures or maintenance may delay creation or delivery."},
    {title:"Intellectual-property reports",body:"If you believe material available through CardeLume infringes your rights, contact the legal address shown below with enough detail to identify the work, the material at issue, your authority and a reliable way to reach you. CardeLume will review good-faith reports and preserve appropriate evidence."}
  ],
  refundTitle:"Refund & First-Purchase Quality Guarantee",refundIntro:"Statutory consumer rights and the Merchant of Record/payment provider’s mandatory rules always prevail. CardeLume also intends to offer a practical quality remedy for genuine delivery or quality failures.",
  refundSections:[
    {title:"When to contact us",body:"Contact support promptly, preferably within 7 days of purchase, if you were charged more than once, payment succeeded but no usable final files were delivered, or the paid export has a material technical defect or materially differs from the selected preview because of a CardeLume error."},
    {title:"How we resolve issues",body:"We may first re-render, restore access, correct the export or otherwise deliver the card you purchased. When that does not reasonably resolve an eligible issue, CardeLume or its Merchant of Record may issue the appropriate refund or other remedy."},
    {title:"Quality guarantee",body:"For a first single-card purchase that is genuinely disappointing despite the delivered files being technically usable, CardeLume may offer a re-creation or refund under the owner-approved launch policy. This voluntary guarantee does not reduce any mandatory consumer right."},
    {title:"Abuse and exclusions",body:"The voluntary guarantee is not intended for fraud, repeated abuse, or claims based solely on content the customer supplied after CardeLume delivered the selected card correctly. Mandatory legal rights remain unaffected."}
  ]
};

function localized(base:LegalCopy,overrides:Partial<LegalCopy>):LegalCopy{return{...base,...overrides};}

export const legalCopy:Record<LocaleCode,LegalCopy>={
  en,
  vi:localized(en,{privacyTitle:"Chính sách quyền riêng tư",privacyIntro:"CardeLume được thiết kế để tạo và giao thiệp kỹ thuật số với lượng dữ liệu cá nhân tối thiểu cần thiết cho dịch vụ.",termsTitle:"Điều khoản sử dụng",termsIntro:"Các điều khoản này áp dụng cho việc tạo, xem trước, mua và tải thiệp kỹ thuật số trên CardeLume.",refundTitle:"Hoàn tiền & Đảm bảo chất lượng lần mua đầu",refundIntro:"Quyền lợi bắt buộc của người tiêu dùng và quy định của Merchant of Record/nhà cung cấp thanh toán luôn được ưu tiên. CardeLume cũng hướng đến cách xử lý thực tế cho lỗi giao hàng hoặc chất lượng thật sự.",contactTitle:"Liên hệ về quyền riêng tư và pháp lý",effectiveLabel:"Ngày hiệu lực"}),
  ja:localized(en,{privacyTitle:"プライバシーポリシー",privacyIntro:"CardeLume は、デジタルグリーティングカードの作成と提供に合理的に必要な最小限の個人データで動作するよう設計されています。",termsTitle:"利用規約",termsIntro:"本規約は CardeLume のカード作成、プレビュー、購入、ダウンロードサービスに適用されます。",refundTitle:"返金・初回購入品質保証",refundIntro:"法令上の消費者権利および Merchant of Record／決済事業者の必須ルールが常に優先されます。",contactTitle:"プライバシー・法務窓口",effectiveLabel:"発効日"}),
  ko:localized(en,{privacyTitle:"개인정보 처리방침",privacyIntro:"CardeLume는 디지털 카드 제작과 전달에 합리적으로 필요한 최소한의 개인정보만 처리하도록 설계되었습니다.",termsTitle:"이용약관",termsIntro:"본 약관은 CardeLume의 카드 제작, 미리보기, 구매 및 다운로드 서비스에 적용됩니다.",refundTitle:"환불 및 첫 구매 품질 보장",refundIntro:"법정 소비자 권리와 Merchant of Record/결제 제공자의 의무 규정이 항상 우선합니다.",contactTitle:"개인정보·법률 문의",effectiveLabel:"시행일"}),
  es:localized(en,{privacyTitle:"Política de privacidad",privacyIntro:"CardeLume está diseñado para crear y entregar tarjetas digitales utilizando únicamente los datos personales razonablemente necesarios para prestar el servicio.",termsTitle:"Términos de uso",termsIntro:"Estos términos se aplican a la creación, vista previa, compra y descarga de tarjetas digitales de CardeLume.",refundTitle:"Reembolsos y garantía de calidad de la primera compra",refundIntro:"Los derechos legales del consumidor y las reglas obligatorias del Merchant of Record/proveedor de pagos prevalecen siempre.",contactTitle:"Contacto de privacidad y legal",effectiveLabel:"Fecha de vigencia"}),
  fr:localized(en,{privacyTitle:"Politique de confidentialité",privacyIntro:"CardeLume est conçu pour créer et livrer des cartes numériques avec le minimum de données personnelles raisonnablement nécessaire au service.",termsTitle:"Conditions d’utilisation",termsIntro:"Ces conditions s’appliquent à la création, l’aperçu, l’achat et au téléchargement de cartes numériques CardeLume.",refundTitle:"Remboursements et garantie qualité du premier achat",refundIntro:"Les droits légaux des consommateurs et les règles obligatoires du Merchant of Record/prestataire de paiement prévalent toujours.",contactTitle:"Contact confidentialité et juridique",effectiveLabel:"Date d’entrée en vigueur"}),
  de:localized(en,{privacyTitle:"Datenschutzerklärung",privacyIntro:"CardeLume ist darauf ausgelegt, digitale Grußkarten mit möglichst wenigen, für den Dienst erforderlichen personenbezogenen Daten zu erstellen und bereitzustellen.",termsTitle:"Nutzungsbedingungen",termsIntro:"Diese Bedingungen gelten für Erstellung, Vorschau, Kauf und Download digitaler CardeLume-Karten.",refundTitle:"Rückerstattung & Qualitätsgarantie beim ersten Kauf",refundIntro:"Gesetzliche Verbraucherrechte und zwingende Regeln des Merchant of Record/Zahlungsanbieters haben stets Vorrang.",contactTitle:"Datenschutz- und Rechtskontakt",effectiveLabel:"Gültig ab"}),
  pt:localized(en,{privacyTitle:"Política de privacidade",privacyIntro:"O CardeLume foi projetado para criar e entregar cartões digitais usando apenas os dados pessoais razoavelmente necessários para o serviço.",termsTitle:"Termos de uso",termsIntro:"Estes termos se aplicam à criação, prévia, compra e download de cartões digitais no CardeLume.",refundTitle:"Reembolso e garantia de qualidade da primeira compra",refundIntro:"Direitos legais do consumidor e regras obrigatórias do Merchant of Record/provedor de pagamentos sempre prevalecem.",contactTitle:"Contato de privacidade e jurídico",effectiveLabel:"Data de vigência"}),
  it:localized(en,{privacyTitle:"Informativa sulla privacy",privacyIntro:"CardeLume è progettato per creare e consegnare biglietti digitali usando solo i dati personali ragionevolmente necessari al servizio.",termsTitle:"Termini di utilizzo",termsIntro:"Questi termini si applicano alla creazione, anteprima, acquisto e download dei biglietti digitali CardeLume.",refundTitle:"Rimborsi e garanzia qualità sul primo acquisto",refundIntro:"I diritti inderogabili dei consumatori e le regole obbligatorie del Merchant of Record/fornitore di pagamento prevalgono sempre.",contactTitle:"Contatto privacy e legale",effectiveLabel:"Data di efficacia"}),
  zh:localized(en,{privacyTitle:"隐私政策",privacyIntro:"CardeLume 的设计目标是在创建和交付数字贺卡时，只处理提供服务所合理需要的最少个人数据。",termsTitle:"使用条款",termsIntro:"本条款适用于 CardeLume 的数字贺卡创建、预览、购买和下载服务。",refundTitle:"退款与首次购买质量保障",refundIntro:"法定消费者权利以及 Merchant of Record/支付服务商的强制规则始终优先适用。",contactTitle:"隐私与法律联系",effectiveLabel:"生效日期"})
};
