import type { LocaleCode } from "./messages";

type RecoveryCopy={
  eyebrow:string;
  ready:string; intro:string; preparing:string; preparingBody:string;
  accessNeeded:string; accessNeededBody:string; expires:string;
  download:string; finalFile:string; jpg:string; pdf:string;
  privateNote:string; keepsakeNote:string; returnWaiting:string; returnWaitingBody:string;
  invalid:string; invalidBody:string;
};

export const recoveryCopy:Record<LocaleCode,RecoveryCopy>={
  en:{eyebrow:"Private purchase recovery",ready:"Your CardeLume files are safe.",intro:"Come back to this private page whenever you need your purchased files.",preparing:"Your clean final is being prepared.",preparingBody:"Payment is confirmed. We’re finishing the private download files now; this page will update automatically.",accessNeeded:"Private recovery access required",accessNeededBody:"Open the secure recovery link from your purchase confirmation on this browser to restore access.",expires:"Recovery access available until",download:"Download",finalFile:"Final card",jpg:"High-resolution JPG",pdf:"Print-ready PDF",privateNote:"Private links are created only when you download and expire shortly after.",keepsakeNote:"These are your files: a high-resolution JPG for sharing and a print-ready PDF to keep and print.",returnWaiting:"Securing your purchase…",returnWaitingBody:"Payment is being confirmed and your private recovery page is being prepared. This will continue automatically.",invalid:"This secure link is no longer available.",invalidBody:"If you chose to receive a recovery email, reopen the link from that message. Otherwise use your original payment confirmation to contact CardeLume support."},
  ja:{eyebrow:"購入ファイルの非公開復元",ready:"CardeLumeの購入ファイルは安全に保管されています。",intro:"購入したファイルが必要なときは、この非公開ページに戻れます。",preparing:"透かしのない最終版を準備しています。",preparingBody:"お支払いは確認済みです。非公開のダウンロードファイルを仕上げています。このページは自動で更新されます。",accessNeeded:"非公開の復元アクセスが必要です",accessNeededBody:"購入確認時の安全な復元リンクをこのブラウザで開いて、アクセスを復元してください。",expires:"復元アクセス期限",download:"ダウンロード",finalFile:"最終版",jpg:"高解像度JPG",pdf:"印刷用PDF",privateNote:"ダウンロード時だけ非公開リンクを発行し、短時間で期限切れになります。",keepsakeNote:"この2つがあなたのファイルです。シェア用の高解像度JPGと、保存・印刷できる印刷用PDFです。",returnWaiting:"購入を安全に引き継いでいます…",returnWaitingBody:"お支払い確認と非公開の復元ページを準備しています。自動で続行します。",invalid:"この安全なリンクは利用できません。",invalidBody:"復元メールを希望した場合は、そのメッセージ内のリンクを開き直してください。それ以外の場合は、購入時の決済情報をもとにCardeLumeサポートへお問い合わせください。"},
  ko:{eyebrow:"구매 파일 비공개 복구",ready:"구매한 CardeLume 파일이 안전하게 보관되어 있어요.",intro:"구매한 파일이 필요할 때 언제든 이 비공개 페이지로 돌아오세요.",preparing:"워터마크 없는 최종본을 준비하고 있어요.",preparingBody:"결제가 확인되었습니다. 비공개 다운로드 파일을 마무리하는 중이며 이 페이지가 자동으로 업데이트됩니다.",accessNeeded:"비공개 복구 접근이 필요합니다",accessNeededBody:"구매 확인 시 받은 안전한 복구 링크를 이 브라우저에서 열어 접근을 복원해 주세요.",expires:"복구 접근 가능 기간",download:"다운로드",finalFile:"최종 카드",jpg:"고해상도 JPG",pdf:"인쇄용 PDF",privateNote:"다운로드할 때만 비공개 링크가 생성되며 짧은 시간 후 만료됩니다.",keepsakeNote:"이 두 파일이 고객님의 최종본입니다: 공유용 고해상도 JPG와 보관·인쇄용 PDF.",returnWaiting:"구매를 안전하게 연결하는 중…",returnWaitingBody:"결제를 확인하고 비공개 복구 페이지를 준비하고 있습니다. 자동으로 계속됩니다.",invalid:"이 안전한 링크는 더 이상 사용할 수 없습니다.",invalidBody:"복구 이메일을 선택했다면 해당 메시지의 링크를 다시 열어 주세요. 그렇지 않다면 결제 확인 정보를 가지고 CardeLume 지원에 문의해 주세요."},
  es:{eyebrow:"Recuperación privada de compra",ready:"Tus archivos de CardeLume están seguros.",intro:"Vuelve a esta página privada cuando necesites los archivos que compraste.",preparing:"Estamos preparando tu versión final limpia.",preparingBody:"El pago está confirmado. Estamos terminando los archivos privados de descarga; esta página se actualizará automáticamente.",accessNeeded:"Se necesita acceso privado de recuperación",accessNeededBody:"Abre en este navegador el enlace seguro de recuperación de la confirmación de compra para restaurar el acceso.",expires:"Acceso de recuperación disponible hasta",download:"Descargar",finalFile:"Tarjeta final",jpg:"JPG de alta resolución",pdf:"PDF listo para imprimir",privateNote:"Los enlaces privados se crean solo al descargar y caducan poco después.",keepsakeNote:"Estos son tus archivos: un JPG de alta resolución para compartir y un PDF listo para imprimir y conservar.",returnWaiting:"Protegiendo tu compra…",returnWaitingBody:"Estamos confirmando el pago y preparando tu página privada de recuperación. Continuará automáticamente.",invalid:"Este enlace seguro ya no está disponible.",invalidBody:"Si elegiste recibir un email de recuperación, vuelve a abrir el enlace de ese mensaje. Si no, usa tu confirmación de pago original para contactar con soporte de CardeLume."},
  fr:{eyebrow:"Récupération privée de l’achat",ready:"Vos fichiers CardeLume sont en sécurité.",intro:"Revenez sur cette page privée chaque fois que vous avez besoin de vos fichiers achetés.",preparing:"Votre version finale sans filigrane est en préparation.",preparingBody:"Le paiement est confirmé. Nous finalisons les fichiers privés à télécharger ; cette page se mettra à jour automatiquement.",accessNeeded:"Accès privé de récupération requis",accessNeededBody:"Ouvrez sur ce navigateur le lien sécurisé de récupération reçu avec la confirmation d’achat afin de restaurer l’accès.",expires:"Accès de récupération disponible jusqu’au",download:"Télécharger",finalFile:"Carte finale",jpg:"JPG haute résolution",pdf:"PDF prêt à imprimer",privateNote:"Les liens privés sont créés uniquement au téléchargement et expirent rapidement.",keepsakeNote:"Ce sont vos fichiers : un JPG haute résolution à partager et un PDF prêt à imprimer à conserver.",returnWaiting:"Sécurisation de votre achat…",returnWaitingBody:"Nous confirmons le paiement et préparons votre page privée de récupération. La suite est automatique.",invalid:"Ce lien sécurisé n’est plus disponible.",invalidBody:"Si vous avez choisi de recevoir un e-mail de récupération, rouvrez le lien de ce message. Sinon, utilisez votre confirmation de paiement pour contacter l’assistance CardeLume."},
  de:{eyebrow:"Private Kaufwiederherstellung",ready:"Ihre CardeLume-Dateien sind sicher.",intro:"Kehren Sie jederzeit zu dieser privaten Seite zurück, wenn Sie Ihre gekauften Dateien benötigen.",preparing:"Ihre saubere Finalversion wird vorbereitet.",preparingBody:"Die Zahlung ist bestätigt. Wir stellen die privaten Download-Dateien fertig; diese Seite aktualisiert sich automatisch.",accessNeeded:"Privater Wiederherstellungszugang erforderlich",accessNeededBody:"Öffnen Sie den sicheren Wiederherstellungslink aus Ihrer Kaufbestätigung in diesem Browser, um den Zugang wiederherzustellen.",expires:"Wiederherstellungszugang verfügbar bis",download:"Herunterladen",finalFile:"Finale Karte",jpg:"Hochauflösendes JPG",pdf:"Druckfertiges PDF",privateNote:"Private Links werden nur beim Download erzeugt und laufen kurz danach ab.",keepsakeNote:"Das sind Ihre Dateien: ein hochauflösendes JPG zum Teilen und ein druckfertiges PDF zum Aufbewahren und Drucken.",returnWaiting:"Ihr Kauf wird sicher verbunden…",returnWaitingBody:"Wir bestätigen die Zahlung und bereiten Ihre private Wiederherstellungsseite vor. Es geht automatisch weiter.",invalid:"Dieser sichere Link ist nicht mehr verfügbar.",invalidBody:"Wenn Sie eine Wiederherstellungs-E-Mail gewählt haben, öffnen Sie den Link aus dieser Nachricht erneut. Andernfalls kontaktieren Sie CardeLume mit Ihrer ursprünglichen Zahlungsbestätigung."},
  pt:{eyebrow:"Recuperação privada da compra",ready:"Seus arquivos CardeLume estão seguros.",intro:"Volte a esta página privada sempre que precisar dos arquivos comprados.",preparing:"Sua versão final limpa está sendo preparada.",preparingBody:"O pagamento foi confirmado. Estamos finalizando os arquivos privados para download; esta página será atualizada automaticamente.",accessNeeded:"É necessário acesso privado de recuperação",accessNeededBody:"Abra neste navegador o link seguro de recuperação da confirmação da compra para restaurar o acesso.",expires:"Acesso de recuperação disponível até",download:"Baixar",finalFile:"Cartão final",jpg:"JPG em alta resolução",pdf:"PDF pronto para imprimir",privateNote:"Links privados são criados apenas no momento do download e expiram pouco depois.",keepsakeNote:"Estes são seus arquivos: um JPG em alta resolução para compartilhar e um PDF pronto para imprimir e guardar.",returnWaiting:"Protegendo sua compra…",returnWaitingBody:"Estamos confirmando o pagamento e preparando sua página privada de recuperação. O processo seguirá automaticamente.",invalid:"Este link seguro não está mais disponível.",invalidBody:"Se você escolheu receber um e-mail de recuperação, abra novamente o link dessa mensagem. Caso contrário, use a confirmação de pagamento original para contatar o suporte CardeLume."},
  it:{eyebrow:"Recupero privato dell’acquisto",ready:"I tuoi file CardeLume sono al sicuro.",intro:"Torna su questa pagina privata ogni volta che hai bisogno dei file acquistati.",preparing:"Stiamo preparando la versione finale pulita.",preparingBody:"Il pagamento è confermato. Stiamo completando i file privati da scaricare; questa pagina si aggiornerà automaticamente.",accessNeeded:"È necessario l’accesso privato di recupero",accessNeededBody:"Apri in questo browser il link sicuro di recupero ricevuto con la conferma d’acquisto per ripristinare l’accesso.",expires:"Accesso di recupero disponibile fino al",download:"Scarica",finalFile:"Biglietto finale",jpg:"JPG ad alta risoluzione",pdf:"PDF pronto per la stampa",privateNote:"I link privati vengono creati solo al momento del download e scadono poco dopo.",keepsakeNote:"Questi sono i tuoi file: un JPG ad alta risoluzione da condividere e un PDF pronto per la stampa da conservare.",returnWaiting:"Stiamo proteggendo il tuo acquisto…",returnWaitingBody:"Stiamo confermando il pagamento e preparando la pagina privata di recupero. Il processo continuerà automaticamente.",invalid:"Questo link sicuro non è più disponibile.",invalidBody:"Se hai scelto di ricevere un’e-mail di recupero, riapri il link contenuto nel messaggio. In caso contrario, usa la conferma di pagamento originale per contattare l’assistenza CardeLume."},
  zh:{eyebrow:"私密购买恢复",ready:"你的CardeLume购买文件已安全保存。",intro:"需要已购买文件时，可随时回到这个私密页面。",preparing:"正在准备无水印最终版。",preparingBody:"付款已确认。我们正在完成私密下载文件，此页面会自动更新。",accessNeeded:"需要私密恢复权限",accessNeededBody:"请在此浏览器打开购买确认中的安全恢复链接，以恢复访问权限。",expires:"恢复访问有效至",download:"下载",finalFile:"最终卡片",jpg:"高清JPG",pdf:"可打印PDF",privateNote:"私密下载链接仅在下载时生成，并会很快过期。",keepsakeNote:"这就是属于你的两份文件：用于分享的高清JPG，以及可长期保存和打印的PDF。",returnWaiting:"正在安全连接你的购买记录…",returnWaitingBody:"我们正在确认付款并准备私密恢复页面，完成后会自动继续。",invalid:"此安全链接已不可用。",invalidBody:"如果你选择接收恢复邮件，请重新打开邮件中的链接；否则请使用原始付款凭证联系CardeLume支持。"},
  vi:{eyebrow:"Khôi phục giao dịch riêng tư",ready:"File CardeLume bạn đã mua đang được giữ an toàn.",intro:"Bạn có thể quay lại trang riêng tư này khi cần tải lại các file đã mua.",preparing:"Bản sạch đang được hoàn thiện.",preparingBody:"Thanh toán đã được xác nhận. CardeLume đang hoàn thiện các file tải xuống riêng tư; trang này sẽ tự cập nhật.",accessNeeded:"Cần quyền khôi phục riêng tư",accessNeededBody:"Hãy mở link khôi phục an toàn trong xác nhận mua hàng trên trình duyệt này để lấy lại quyền truy cập.",expires:"Quyền khôi phục có hiệu lực đến",download:"Tải xuống",finalFile:"Thiệp hoàn chỉnh",jpg:"JPG độ phân giải cao",pdf:"PDF sẵn sàng in",privateNote:"Link tải riêng tư chỉ được tạo khi bạn tải file và sẽ hết hạn sau thời gian ngắn.",keepsakeNote:"Đây là hai file thuộc về bạn: JPG độ phân giải cao để chia sẻ và PDF sẵn sàng in để lưu giữ lâu dài.",returnWaiting:"Đang bảo vệ giao dịch của bạn…",returnWaitingBody:"CardeLume đang xác nhận thanh toán và chuẩn bị trang khôi phục riêng tư. Quá trình sẽ tự tiếp tục.",invalid:"Link an toàn này không còn khả dụng.",invalidBody:"Nếu bạn đã chọn nhận email khôi phục, hãy mở lại link trong email đó. Nếu không, hãy dùng xác nhận thanh toán ban đầu để liên hệ hỗ trợ CardeLume."}
};
