"use client";
import { useEffect,useMemo,useState } from "react";
import { portfolioV2AllTemplates,type Affinity,type TemplateMeta } from "@cardelume/templates";

const split=(v:string)=>v.split(",").map(x=>x.trim()).filter(Boolean);
const parseAffinity=(v:string)=>split(v).map(entry=>{const [key,...rest]=entry.split(":");const raw=Number(rest.join(":"));const score=Number.isFinite(raw)?Math.max(0,Math.min(100,raw))/100:.9;return{key:key.trim(),score};}).filter(x=>x.key);
const affinityText=(items:Affinity[],excludeGlobal=false)=>items.filter(x=>(!excludeGlobal||x.key!=="GLOBAL")&&x.score>0).map(x=>`${x.key}:${Math.round(x.score*100)}`).join(",");
const slugify=(v:string)=>v.toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/(^-|-$)/g,"").slice(0,80);

type VersionForm={rendererTemplateKey:string;headlineCapacity:"short"|"medium"|"long";bodyCapacity:"short"|"medium"|"long";activate:boolean};

type FunnelPulse={event_type:string;events:number;subjects:number};

export function TemplateAdmin(){
  const [pulse,setPulse]=useState<FunnelPulse[]>([]);
  const [items,setItems]=useState<TemplateMeta[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState(""),[editing,setEditing]=useState<TemplateMeta|null>(null),[versioning,setVersioning]=useState<TemplateMeta|null>(null),[launching,setLaunching]=useState<TemplateMeta|null>(null),[query,setQuery]=useState(""),[statusFilter,setStatusFilter]=useState("all");
  const [editMeta,setEditMeta]=useState({name:"",material:"",editorialScore:"85",feelings:"",occasions:"",markets:"",excludedMarkets:""});
  const [form,setForm]=useState({name:"",slug:"",familyId:"",material:"",rendererTemplateKey:"luxury-editorial",photoMode:"none",editorialScore:"85",feelings:"Elegant:90,Warm:80",occasions:"Birthday:90",markets:""});
  const [versionForm,setVersionForm]=useState<VersionForm>({rendererTemplateKey:"luxury-editorial",headlineCapacity:"medium",bodyCapacity:"medium",activate:true});
  const [launchForm,setLaunchForm]=useState({benchmarkEvidence:"",ipEvidence:"",humanReviewEvidence:"",note:""});

  async function load(){const [r,p]=await Promise.all([fetch("/api/admin/templates",{cache:"no-store"}),fetch("/api/admin/funnel?days=30",{cache:"no-store"})]);const j=await r.json();if(r.ok){setItems(j.templates??[]);setError("");}else setError(j.error??"Unable to load");if(p.ok){const pj=await p.json();setPulse(pj.events??[]);}}
  useEffect(()=>{void load()},[]);
  const rendererKeys=useMemo(()=>[...new Set(portfolioV2AllTemplates.map(t=>t.rendererTemplateKey))],[]);
  const families=useMemo(()=>{const seen=new Set<string>();return items.filter(t=>{if(seen.has(t.familyId))return false;seen.add(t.familyId);return true;});},[items]);
  const visibleItems=useMemo(()=>items.filter(t=>(statusFilter==="all"||t.status===statusFilter)&&(!query||`${t.name} ${t.slug} ${t.markets.map(x=>x.key).join(" ")} ${t.feelings.map(x=>x.key).join(" ")}`.toLowerCase().includes(query.toLowerCase()))),[items,query,statusFilter]);

  async function create(){setBusy(true);setError("");const r=await fetch("/api/admin/templates",{method:"POST",headers:{"content-type":"application/json","x-cardelume-admin-action":"1"},body:JSON.stringify({name:form.name,slug:form.slug,familyId:form.familyId||undefined,material:form.material,rendererTemplateKey:form.rendererTemplateKey,photoMode:form.photoMode,editorialScore:Number(form.editorialScore),feelings:parseAffinity(form.feelings),occasions:parseAffinity(form.occasions),markets:parseAffinity(form.markets)})});const j=await r.json();if(!r.ok)setError(j.error??"Create failed");else{setForm({...form,name:"",slug:"",material:"",familyId:""});await load()}setBusy(false);}
  function duplicate(t:TemplateMeta){setForm({name:`${t.name} Variant`,slug:`${t.slug}-variant`,familyId:t.familyId,material:t.material,rendererTemplateKey:t.rendererTemplateKey,photoMode:t.photoMode,editorialScore:String(t.editorialScore),feelings:affinityText(t.feelings),occasions:affinityText(t.occasions),markets:affinityText(t.markets,true)});window.scrollTo({top:0,behavior:"smooth"});}
  function beginEdit(t:TemplateMeta){setEditing(t);setEditMeta({name:t.name,material:t.material,editorialScore:String(t.editorialScore),feelings:affinityText(t.feelings),occasions:affinityText(t.occasions),markets:affinityText(t.markets,true),excludedMarkets:t.excludedMarkets.join(",")});}
  async function saveEdit(){if(!editing)return;setBusy(true);setError("");const r=await fetch(`/api/admin/templates/${editing.id}`,{method:"PATCH",headers:{"content-type":"application/json","x-cardelume-admin-action":"1"},body:JSON.stringify({name:editMeta.name,material:editMeta.material,editorialScore:Number(editMeta.editorialScore),feelings:parseAffinity(editMeta.feelings),occasions:parseAffinity(editMeta.occasions),markets:parseAffinity(editMeta.markets),excludedMarkets:split(editMeta.excludedMarkets)})});const j=await r.json();if(!r.ok)setError(j.error??"Update failed");else{setEditing(null);await load()}setBusy(false);}
  function beginVersion(t:TemplateMeta){setVersioning(t);setVersionForm({rendererTemplateKey:t.rendererTemplateKey,headlineCapacity:t.headlineCapacity,bodyCapacity:t.bodyCapacity,activate:true});}
  async function createVersion(){if(!versioning)return;setBusy(true);setError("");const r=await fetch(`/api/admin/templates/${versioning.id}/versions`,{method:"POST",headers:{"content-type":"application/json","x-cardelume-admin-action":"1"},body:JSON.stringify({rendererTemplateKey:versionForm.rendererTemplateKey,supportedFormats:versioning.supportedFormats,scriptSupport:versioning.scriptSupport,headlineCapacity:versionForm.headlineCapacity,bodyCapacity:versionForm.bodyCapacity,activate:versionForm.activate})});const j=await r.json();if(!r.ok)setError(j.error??"Version create failed");else{setVersioning(null);await load()}setBusy(false);}
  function beginLaunch(t:TemplateMeta){setLaunching(t);setLaunchForm({benchmarkEvidence:"",ipEvidence:"",humanReviewEvidence:"",note:""});}
  async function decideLaunch(decision:"approved"|"candidate"|"hold"|"rework"|"rejected"){
    if(!launching)return;setBusy(true);setError("");
    const r=await fetch(`/api/admin/templates/${launching.id}/launch`,{method:"POST",headers:{"content-type":"application/json","x-cardelume-admin-action":"1"},body:JSON.stringify({decision,...launchForm})});
    const j=await r.json();if(!r.ok)setError(j.error??"Launch decision failed");else{setLaunching(null);await load()}setBusy(false);
  }
  async function patch(id:string,data:object){setBusy(true);setError("");const r=await fetch(`/api/admin/templates/${id}`,{method:"PATCH",headers:{"content-type":"application/json","x-cardelume-admin-action":"1"},body:JSON.stringify(data)});const j=await r.json();if(!r.ok)setError(j.error??"Update failed");await load();setBusy(false);}
  async function archive(id:string){if(!confirm("Remove this template from selection? Existing purchases keep their immutable version."))return;setBusy(true);const r=await fetch(`/api/admin/templates/${id}`,{method:"DELETE",headers:{"x-cardelume-admin-action":"1"}});const j=await r.json();if(!r.ok)setError(j.error??"Archive failed");await load();setBusy(false);}

  return <main className="admin-template-page">
    <header><div><span>CardeLume Admin</span><h1>Template Library</h1></div><b>{items.filter(x=>x.status==="active").length} active · {items.length} total</b></header>
    {error?<p className="admin-error">{error}</p>:null}
    <section className="admin-pulse" aria-label="30 day operating pulse"><div><small>30-day operating pulse</small><strong>{pulse.find(x=>x.event_type==="studio_started")?.subjects??0}</strong><span>studio visitors</span></div><div><small>Generated</small><strong>{pulse.find(x=>x.event_type==="results_viewed")?.subjects??0}</strong><span>unique subjects</span></div><div><small>Checkout</small><strong>{pulse.find(x=>x.event_type==="checkout_started")?.subjects??0}</strong><span>unique subjects</span></div><div><small>Paid</small><strong>{pulse.find(x=>x.event_type==="payment_completed")?.subjects??0}</strong><span>verified purchases</span></div><div><small>Final render</small><strong>{pulse.find(x=>x.event_type==="final_render_completed")?.events??0}</strong><span>completed</span></div></section>
    <section className="admin-create"><h2>Add template</h2><div className="admin-form-grid">
      <input placeholder="Template name" value={form.name} onChange={e=>setForm({...form,name:e.target.value,slug:form.slug||slugify(e.target.value)})}/>
      <input placeholder="slug-name" value={form.slug} onChange={e=>setForm({...form,slug:slugify(e.target.value)})}/>
      <select value={form.familyId} onChange={e=>setForm({...form,familyId:e.target.value})}><option value="">New template family</option>{families.map(x=><option value={x.familyId} key={x.familyId}>Variant of {x.name}</option>)}</select>
      <input placeholder="Material / finish" value={form.material} onChange={e=>setForm({...form,material:e.target.value})}/>
      <select value={form.rendererTemplateKey} onChange={e=>setForm({...form,rendererTemplateKey:e.target.value,photoMode:portfolioV2AllTemplates.find(t=>t.rendererTemplateKey===e.target.value)?.photoMode??"none"})}>{rendererKeys.map(x=><option key={x}>{x}</option>)}</select>
      <select value={form.photoMode} onChange={e=>setForm({...form,photoMode:e.target.value})}><option value="none">No photo</option><option value="optional">Photo optional</option><option value="required">Photo required</option></select>
      <input type="number" min="0" max="100" value={form.editorialScore} onChange={e=>setForm({...form,editorialScore:e.target.value})}/>
      <input placeholder="Feelings: Elegant:95,Warm:80" value={form.feelings} onChange={e=>setForm({...form,feelings:e.target.value})}/>
      <input placeholder="Occasions: Birthday:90" value={form.occasions} onChange={e=>setForm({...form,occasions:e.target.value})}/>
      <input placeholder="Markets: VN:95,JP:80" value={form.markets} onChange={e=>setForm({...form,markets:e.target.value})}/>
    </div><button disabled={busy||!form.name||!form.slug} onClick={create}>Add as draft</button><p>Scores are 0–100. Use an existing family for a market/style variant so AI diversity never shows near-duplicates together. New entries can only reuse renderer keys that already passed CardeLume render QA.</p></section>

    {editing?<section className="admin-create admin-edit"><h2>Edit {editing.name}</h2><div className="admin-form-grid"><input value={editMeta.name} onChange={e=>setEditMeta({...editMeta,name:e.target.value})}/><input placeholder="Material" value={editMeta.material} onChange={e=>setEditMeta({...editMeta,material:e.target.value})}/><input type="number" min="0" max="100" value={editMeta.editorialScore} onChange={e=>setEditMeta({...editMeta,editorialScore:e.target.value})}/><input placeholder="Feelings: Warm:95" value={editMeta.feelings} onChange={e=>setEditMeta({...editMeta,feelings:e.target.value})}/><input placeholder="Occasions" value={editMeta.occasions} onChange={e=>setEditMeta({...editMeta,occasions:e.target.value})}/><input placeholder="Preferred markets" value={editMeta.markets} onChange={e=>setEditMeta({...editMeta,markets:e.target.value})}/><input placeholder="Excluded markets" value={editMeta.excludedMarkets} onChange={e=>setEditMeta({...editMeta,excludedMarkets:e.target.value})}/></div><button disabled={busy} onClick={saveEdit}>Save metadata</button><button disabled={busy} onClick={()=>setEditing(null)}>Cancel</button><p>Metadata/targeting is mutable. Pixel-affecting renderer/layout changes create a new immutable version instead.</p></section>:null}

    {versioning?<section className="admin-create admin-edit"><h2>New immutable version · {versioning.name} v{versioning.version}</h2><div className="admin-form-grid"><select value={versionForm.rendererTemplateKey} onChange={e=>setVersionForm({...versionForm,rendererTemplateKey:e.target.value})}>{rendererKeys.map(x=><option key={x}>{x}</option>)}</select><select value={versionForm.headlineCapacity} onChange={e=>setVersionForm({...versionForm,headlineCapacity:e.target.value as VersionForm["headlineCapacity"]})}><option>short</option><option>medium</option><option>long</option></select><select value={versionForm.bodyCapacity} onChange={e=>setVersionForm({...versionForm,bodyCapacity:e.target.value as VersionForm["bodyCapacity"]})}><option>short</option><option>medium</option><option>long</option></select><label><input type="checkbox" checked={versionForm.activate} onChange={e=>setVersionForm({...versionForm,activate:e.target.checked})}/> Activate after creation</label></div><button disabled={busy} onClick={createVersion}>Create v{versioning.version+1}</button><button disabled={busy} onClick={()=>setVersioning(null)}>Cancel</button><p>Only pre-QA renderer keys are allowed here. Existing orders remain pinned to the version they previewed and purchased.</p></section>:null}

    {launching?<section className="admin-create admin-edit"><h2>Launch review · {launching.name} v{launching.version}</h2><p>Technical activation is not launch approval. Approval is version-bound and requires benchmark, IP and human-review evidence.</p><div className="admin-form-grid">
      <input placeholder="Golden benchmark evidence ID / report path" value={launchForm.benchmarkEvidence} onChange={e=>setLaunchForm({...launchForm,benchmarkEvidence:e.target.value})}/>
      <input placeholder="IP/originality evidence ID / report path" value={launchForm.ipEvidence} onChange={e=>setLaunchForm({...launchForm,ipEvidence:e.target.value})}/>
      <input placeholder="Human premium/WOW review evidence" value={launchForm.humanReviewEvidence} onChange={e=>setLaunchForm({...launchForm,humanReviewEvidence:e.target.value})}/>
      <input placeholder="Decision note (optional)" value={launchForm.note} onChange={e=>setLaunchForm({...launchForm,note:e.target.value})}/>
    </div><div className="admin-launch-actions"><button disabled={busy||!launchForm.benchmarkEvidence||!launchForm.ipEvidence||!launchForm.humanReviewEvidence} onClick={()=>decideLaunch("approved")}>Approve for launch</button><button disabled={busy} onClick={()=>decideLaunch("candidate")}>Candidate</button><button disabled={busy} onClick={()=>decideLaunch("hold")}>Hold</button><button disabled={busy} onClick={()=>decideLaunch("rework")}>Needs rework</button><button disabled={busy} onClick={()=>setLaunching(null)}>Cancel</button></div></section>:null}

    <div className="admin-library-filters"><input placeholder="Search name, market, feeling…" value={query} onChange={e=>setQuery(e.target.value)}/><select value={statusFilter} onChange={e=>setStatusFilter(e.target.value)}><option value="all">All statuses</option><option value="active">Active</option><option value="draft">Draft</option><option value="archived">Archived</option></select><span>{visibleItems.length} shown</span></div>
    <section className="admin-table-wrap"><table><thead><tr><th>Template</th><th>Status</th><th>Market / feeling</th><th>Photo</th><th>Editorial</th><th>30d use</th><th>AI</th><th>Paid</th><th>Actions</th></tr></thead><tbody>{visibleItems.map(t=><tr key={t.id}><td><b>{t.name} · v{t.version}</b><small>{t.slug} · {t.rendererTemplateKey}</small></td><td>{t.status} / {t.health}<small>launch: {t.launchStatus}</small></td><td><small>{t.markets.filter(x=>x.key!=="GLOBAL"&&x.score>=.7).map(x=>x.key).join(", ")||"Global"}<br/>{t.feelings.filter(x=>x.score>=.75).slice(0,3).map(x=>x.key).join(", ")}</small></td><td>{t.photoMode}</td><td>{t.editorialScore}</td><td>{t.impressions??0} impressions · {t.selected??0} selected</td><td>{t.aiAssigned??0} assigned · {t.checkoutStarted??0} checkout</td><td>{t.paid??0} · {t.impressions?((t.paid??0)/t.impressions*100).toFixed(1):"0.0"}%/imp</td><td><button disabled={busy} onClick={()=>beginEdit(t)}>Edit</button><button disabled={busy} onClick={()=>duplicate(t)}>Duplicate</button><button disabled={busy} onClick={()=>beginVersion(t)}>New version</button><button disabled={busy} onClick={()=>beginLaunch(t)}>Launch review</button><button disabled={busy||t.status==="active"} onClick={()=>patch(t.id,{status:"active"})}>Technical publish</button><button disabled={busy||t.status==="draft"} onClick={()=>patch(t.id,{status:"draft"})}>Draft</button><button disabled={busy||t.status==="archived"} onClick={()=>archive(t.id)}>Remove</button></td></tr>)}</tbody></table></section>
  </main>;
}
