import { randomUUID } from "node:crypto";
import { NextResponse } from "next/server";
import { z } from "zod";
import { recordStyleFingerprint, recordTemplateEvent } from "@cardelume/db";
import { normalizeMarket } from "../../../../lib/pricing";
import { anonymousIdFromCookieHeader } from "../../../../lib/pricing-quote.server";
import { checkUserRateLimit } from "../../../../lib/rate-limit.server";
import { templateEventDedupeKey, verifyTemplateEventToken } from "../../../../lib/template-event-token.server";
const Event=z.object({templateId:z.string().uuid(),templateVersionId:z.string().uuid(),eventType:z.enum(["impression","selected","regenerated"]),source:z.enum(["recommended","market_pick","show_more","ai_direction"]),rankPosition:z.number().int().min(1).max(24),locale:z.string().min(2).max(20),eventToken:z.string().min(40).max(2048)});
const Body=z.object({events:z.array(Event).min(1).max(24)});
export async function POST(req:Request){const parsed=Body.safeParse(await req.json().catch(()=>null));if(!parsed.success)return NextResponse.json({error:"template_events_invalid"},{status:400});const anon=anonymousIdFromCookieHeader(req.headers.get("cookie"));if(!anon)return NextResponse.json({error:"anonymous_session_required"},{status:401});const rate=await checkUserRateLimit("template_events",anon).catch(()=>null);if(!rate)return NextResponse.json({error:"template_events_unavailable"},{status:503});if(!rate.allowed)return NextResponse.json({error:"rate_limited"},{status:429,headers:{"retry-after":String(rate.retryAfterSeconds)}});const market=normalizeMarket(req.headers.get("cf-ipcountry")??req.headers.get("x-vercel-ip-country")??req.headers.get("x-country-code"));for(const e of parsed.data.events){if(!verifyTemplateEventToken(e.eventToken,{templateId:e.templateId,templateVersionId:e.templateVersionId,source:e.source,rankPosition:e.rankPosition,market,locale:e.locale,anonymousId:anon}))return NextResponse.json({error:"template_event_forbidden"},{status:403});}try{await Promise.all(parsed.data.events.map(async ({eventToken,...e})=>{const dedupeKey=e.eventType==="regenerated"?undefined:templateEventDedupeKey(eventToken,anon,e.eventType);await recordTemplateEvent({eventId:randomUUID(),...e,market,dedupeKey});if(e.eventType==="selected")await recordStyleFingerprint({id:randomUUID(),userId:anon,templateId:e.templateId,templateVersionId:e.templateVersionId,source:"selected",sourceKey:dedupeKey?`selected:${dedupeKey}`:undefined}).catch(()=>undefined);}));return NextResponse.json({ok:true},{headers:{"cache-control":"no-store"}});}catch{return NextResponse.json({error:"template_events_unavailable"},{status:503});}}
