import { existsSync,readFileSync } from "node:fs";
function need(value:boolean,message:string){if(!value)throw new Error(message);}
const root=(path:string)=>readFileSync(path,"utf8");
const migration=root("packages/db/migrations/0007_production_operations.sql");
const ops=root("packages/db/src/operations.ts");
const ready=root("apps/web/app/health/ready/route.ts");
const workerHealth=root("apps/web/app/health/worker/route.ts");
const worker=root("apps/worker/src/index.ts");
const generation=root("apps/web/app/api/generate/route.ts");
const upload=root("apps/web/app/api/uploads/photo/route.ts");
const checkout=root("apps/web/app/api/checkout/route.ts");
const watchdog=root("infra/watchdog/cardelume-health-watchdog.sh");
const queue=root("packages/queue/src/index.ts");
const compose=root("docker-compose.yml");
need(migration.includes("request_rate_buckets")&&migration.includes("worker_heartbeats enable row level security"),"operations migration missing");
need(ops.includes("upsertWorkerHeartbeat")&&ops.includes("productionReadiness")&&ops.includes("consumeRateLimit")&&ops.includes("removeWorkerHeartbeat"),"operations DB boundary incomplete");
need(ready.includes("validateLiveRuntimeConfig")&&ready.includes("worker_unavailable")&&ready.includes("database_unavailable")&&ready.includes("requiredVersion"),"readiness fail-closed/version boundary missing");
need(!ready.includes("missing:config.missing,invalid:config.invalid,version")||ready.includes('NODE_ENV!=="production"'),"production readiness leaks configuration detail");
need(workerHealth.includes("productionReadiness")&&!workerHealth.includes('status:"unknown"'),"worker heartbeat endpoint not wired");
need(worker.includes("upsertWorkerHeartbeat")&&worker.includes("removeWorkerHeartbeat")&&worker.includes("tracked(async()=>"),"worker heartbeat/activity tracking incomplete");
need(worker.includes("cleanupRateLimitBuckets")&&worker.includes("cleanupStaleWorkerHeartbeats"),"operations cleanup missing");
for(const [name,source] of [["generation",generation],["upload",upload],["checkout",checkout]] as const)need(source.includes("checkUserRateLimit"),`${name} rate limit missing`);
need(watchdog.includes("/health/ready")&&!watchdog.includes("/health/live"),"watchdog still routes traffic on liveness only");
need(!queue.includes("artwork:")&&!queue.includes("preview:"),"unused queue scaffold remains active");
need(!checkout.includes("status:501"),"launch checkout still exposes 501");
need(/cloudflare\/cloudflared:2026\.\d+\.\d+@sha256:[0-9a-f]{64}/.test(compose)&&!compose.includes("cloudflare/cloudflared:latest")&&compose.includes("/health/ready"),"deployment image/readiness not hardened");
need(existsSync("apps/web/lib/production-config.server.ts"),"production config validator missing");
need(root("apps/web/lib/production-config.server.ts").includes("LEGAL_CONTENT_APPROVED"),"legal launch gate missing");
console.log("production operations source stress: PASS");
